version: '3.8'

services:
  tw_stocker_crawler:
    image: nk7260ynpa/tw_stocker_crawler:latest
    container_name: tw_stocker_crawler
    ports:
      - "6738:6738"
    restart: "always"
    networks:
      - db_network

  tw_stocker_daily_upload:
    image: nk7260ynpa/tw_stock_db_operating:2.0.0
    container_name: tw_stocker_daily_upload
    ports:
      - "8080:8080"
    volumes:
      - ../logs:/workspace/logs
    restart: "always"
    networks:
      - db_network

networks:
  db_network:
    external: true
